### ISSUE TITLE
Change navbar color

### ISSUE THREAD

**Issue by Omikorin** [informatyzacja/parliamentary-system#170]
Navbar should be in some main color to separate content from clickable actions (I think according to the visual book to match the best color scheme for the site). Changing background of site to more gray is considerable

Consider that the current logo is in SVG and with transparency - preferred conversion to WEBP with a white background or a background consistent with the visual book and good taste

![obraz](https://user-images.githubusercontent.com/6079265/226186878-443d2259-9902-41e5-9d2a-e28e578cfaa3.png)

**Comment by StachowiakDawid** [comment]
Why not SVG?

**Comment by StachowiakDawid** [comment]
My proposition: var(--chakra-colors-gray-50)
