### ISSUE TITLE
Add database seeder

### ISSUE THREAD

**Issue by Omikorin** [informatyzacja/parliamentary-system#47]
We need database seeder at first run of project

**Comment by StachowiakDawid** [comment]
Idea: scrap and hash data from production DB.

**Comment by Omikorin** [comment]
> Idea: scrap and hash data from production DB.

yeah but you need to remove real people's data (Students and Users)

**Comment by StachowiakDawid** [comment]
We will get test VPS soon, we can simply export data from the test server.
